name: Waypoints
version: 1.3.3
main: com.github.sessional.waypoints.WpsPlugin
softdepend: [dynmap]
commands:
  wps:
    description: A root command
    usage: /<command> [subcommand] [args]
  waypoints:
    description: A root command
    usage: /<command> [subcommand] [args]