name: Waypoints
version: 2.4
main: waypoints.WaypointPlugin
softdepend: [dynmap]
commands:
  wps:
    description: A root command
    usage: /<command> [subcommand] [args]
  waypoints:
    description: A root command
    usage: /<command> [subcommand] [args]